// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_msg_id.proto

#include "proto_msg_id.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Proto {
}  // namespace Proto
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_proto_5fmsg_5fid_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_proto_5fmsg_5fid_2eproto = nullptr;
const uint32_t TableStruct_proto_5fmsg_5fid_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_proto_5fmsg_5fid_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022proto_msg_id.proto\022\005Proto*o\n\005MsgId\022\010\n\004"
  "None\020\000\022\016\n\nMI_TestMsg\020\001\022\025\n\020C2L_AccountChe"
  "ck\020\350\007\022\027\n\022C2L_AccountCheckRs\020\351\007\022\034\n\027MI_Acc"
  "ountCheckToHttpRs\020\355\007b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_proto_5fmsg_5fid_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_proto_5fmsg_5fid_2eproto = {
    false, false, 148, descriptor_table_protodef_proto_5fmsg_5fid_2eproto,
    "proto_msg_id.proto",
    &descriptor_table_proto_5fmsg_5fid_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_proto_5fmsg_5fid_2eproto::offsets,
    nullptr, file_level_enum_descriptors_proto_5fmsg_5fid_2eproto,
    file_level_service_descriptors_proto_5fmsg_5fid_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_proto_5fmsg_5fid_2eproto_getter() {
  return &descriptor_table_proto_5fmsg_5fid_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_proto_5fmsg_5fid_2eproto(&descriptor_table_proto_5fmsg_5fid_2eproto);
namespace Proto {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MsgId_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_proto_5fmsg_5fid_2eproto);
  return file_level_enum_descriptors_proto_5fmsg_5fid_2eproto[0];
}
bool MsgId_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 1000:
    case 1001:
    case 1005:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Proto
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
